apiVersion: v1
kind: Service
metadata:
  namespace: fiap
  name: video-processor-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: video-processor
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      name: video-processor-load-balancer
